// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3N_wvt70LstyDsrnvjzKHVgGON5aSMyg',
    appId: '1:904628078733:web:fb2855ae5f926937d73ac4',
    messagingSenderId: '904628078733',
    projectId: 'chat-app-be9a3',
    authDomain: 'chat-app-be9a3.firebaseapp.com',
    storageBucket: 'chat-app-be9a3.appspot.com',
    measurementId: 'G-LD48SQHMPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-CSKwUXpG5_XPkJ9an-6LwRkC7eAhXk',
    appId: '1:904628078733:android:1a2068c8571f8077d73ac4',
    messagingSenderId: '904628078733',
    projectId: 'chat-app-be9a3',
    storageBucket: 'chat-app-be9a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2nEWUFRHdrDxh-H2S70UIGQ0g5NQauss',
    appId: '1:904628078733:ios:d2b27a5aed355982d73ac4',
    messagingSenderId: '904628078733',
    projectId: 'chat-app-be9a3',
    storageBucket: 'chat-app-be9a3.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2nEWUFRHdrDxh-H2S70UIGQ0g5NQauss',
    appId: '1:904628078733:ios:d2b27a5aed355982d73ac4',
    messagingSenderId: '904628078733',
    projectId: 'chat-app-be9a3',
    storageBucket: 'chat-app-be9a3.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3N_wvt70LstyDsrnvjzKHVgGON5aSMyg',
    appId: '1:904628078733:web:7440211bc7865b0dd73ac4',
    messagingSenderId: '904628078733',
    projectId: 'chat-app-be9a3',
    authDomain: 'chat-app-be9a3.firebaseapp.com',
    storageBucket: 'chat-app-be9a3.appspot.com',
    measurementId: 'G-JSYNLWY8F2',
  );
}
